# 数据源类型 (支持 mysql, postgresql, oracle, sqlserver, excel)
sourceType=excel

# Excel文件路径
excel.filePath=../docs/表结构一览.xlsm

# 代码生成基础包路径
base.package=cn.kunter.generator.demo

# 表前缀忽略，多个用逗号隔开
table.prefix.ignore=sys_,t_

# 移除的公共字段，多个用逗号隔开
table.column.remove=create_time,update_time

# 是否生成标准 RESTful 接口 (默认 true，设为 false 则全用 POST)
controller.restful=true

# 当 controller.restful=false 时，是否允许查询类接口继续使用 @GetMapping
#controller.allowGet=true

# 【核心特性】覆盖保护策略
# 如果为 false，对于已存在的文件（如 Service/Controller）将跳过，仅覆盖模型类。
#file.override=false

# 【核心架构特性】无痕开发模式 (与 dynamic-sql-plus 结合)
# 开启后，将彻底改变持久层架构，实体自动追加 @DynamicMapper，Dao变为防腐层。
#dynamic.plus.enable=false
